node_list:
    path: /nodes
    controller: Adshares\AdsOperator\Controller\Blockexplorer\NodeController::listAction
    methods: [GET]

block_list:
    path: /blocks
    controller: Adshares\AdsOperator\Controller\Blockexplorer\BlockController::listAction
    methods: [GET]

account_list:
    path: /accounts
    controller: Adshares\AdsOperator\Controller\Blockexplorer\AccountController::listAction
    methods: [GET]

message_list:
    path: /messages
    controller: Adshares\AdsOperator\Controller\Blockexplorer\MessageController::listAction
    methods: [GET]

transaction_list:
    path: /transactions
    controller: Adshares\AdsOperator\Controller\Blockexplorer\TransactionController::listAction
    methods: [GET]

node_show:
    path: /nodes/{id}
    controller: Adshares\AdsOperator\Controller\Blockexplorer\NodeController::showAction
    methods: [GET]

block_show:
    path: /blocks/{id}
    controller: Adshares\AdsOperator\Controller\Blockexplorer\BlockController::showAction
    methods: [GET]

account_show:
    path: /accounts/{id}
    controller: Adshares\AdsOperator\Controller\Blockexplorer\AccountController::showAction
    methods: [GET]

message_show:
    path: /messages/{id}
    controller: Adshares\AdsOperator\Controller\Blockexplorer\MessageController::showAction
    methods: [GET]

transaction_show:
    path: /transactions/{id}
    controller: Adshares\AdsOperator\Controller\Blockexplorer\TransactionController::showAction
    methods: [GET]

account_list_by_nodeid:
    path: /nodes/{nodeId}/accounts
    controller: Adshares\AdsOperator\Controller\Blockexplorer\NodeController::accountsAction
    methods: [GET]

message_list_by_nodeid:
    path: /nodes/{nodeId}/messages
    controller: Adshares\AdsOperator\Controller\Blockexplorer\NodeController::messagesAction
    methods: [GET]

transaction_list_by_nodeid:
    path: /nodes/{nodeId}/transactions
    controller: Adshares\AdsOperator\Controller\Blockexplorer\NodeController::transactionsAction
    methods: [GET]

transaction_list_by_accountid:
    path: /accounts/{accountId}/transactions
    controller: Adshares\AdsOperator\Controller\Blockexplorer\AccountController::transactionsAction
    methods: [GET]

message_list_by_blockid:
    path: /blocks/{blockId}/messages
    controller: Adshares\AdsOperator\Controller\Blockexplorer\BlockController::messagesAction
    methods: [GET]

transaction_list_by_blockid:
    path: /blocks/{blockId}/transactions
    controller: Adshares\AdsOperator\Controller\Blockexplorer\BlockController::transactionsAction
    methods: [GET]

transaction_list_by_messageId:
    path: /messages/{messageId}/transactions
    controller: Adshares\AdsOperator\Controller\Blockexplorer\MessageController::transactionsAction
    methods: [GET]
