Adshares\AdsOperator\Document\Transaction:
    discriminatorField: type
    discriminator:
        disabled: false
        field_name: type
        map:
            broadcast: Adshares\AdsOperator\Document\Transaction\BroadcastTransaction
            connection: Adshares\AdsOperator\Document\Transaction\ConnectionTransaction
            empty: Adshares\AdsOperator\Document\Transaction\EmptyTransaction
            key: Adshares\AdsOperator\Document\Transaction\KeyTransaction
            log_account: Adshares\AdsOperator\Document\Transaction\LogAccountTransaction
            send_one: Adshares\AdsOperator\Document\Transaction\SendOneTransaction
            send_many: Adshares\AdsOperator\Document\Transaction\SendManyTransaction
            status: Adshares\AdsOperator\Document\Transaction\StatusTransaction